name: Halal Crypto Bot

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install libraries
        run: pip install ccxt requests
      - name: Run the bot
        env:
           TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          GOOGLE_SCRIPT_URL: ${{ secrets.GOOGLE_SCRIPT_URL }}
        run: python bot.py
